### ISSUE TITLE
k8s ingress

### ISSUE THREAD

**Issue by xinwendewen** [xinwendewen/dive-into-docker#2]
[官网文档](https://kubernetes.io/docs/concepts/services-networking/ingress/#what-is-ingress) [中文](https://www.kubernetes.org.cn/ingress)

**Comment by xinwendewen** [comment]
## What is Ingress

An Ingress is a collection of rules that allow inbound connections to reach the cluster services

是否可以简单理解为ingressn用于与外部网络对接

```yaml
spec:
  rules:
  - http:
      paths:
      - path: /testpath
        backend:
          serviceName: test
          servicePort: 80
```
spec：路由规则，暂时只支持http协议
http rule
- host，默认*
- paths
发来的请求需要对应为host与path对应

### Single Service Ingress

### 查看


## Q
### [service](https://kubernetes.io/docs/concepts/services-networking/service/)概念？

一组pod的抽象，用lable标识

pod是动态创建销毁的，其IP会变化，多个pod之间如何找到对方，把一组pod抽象为服务，其他组建只关心服务，不关注服务内pod的变化

### Pod由谁创建？
[ReplicationControllers](https://kubernetes.io/docs/concepts/workloads/controllers/replicationcontroller/)
